[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "python-telegram-bot[job-queue]>=22.3",
    "replit>=4.1.2",
    "telegram>=0.0.1",
]
